/**
 * Generates a well-formatted markdown string from an AuditReport.
 * Designed to render cleanly in Google Docs, GitHub, and any markdown viewer.
 */

import type { AuditReport } from "@/types/audit";

export function generateMarkdownReport(
  report: AuditReport,
  originalContent?: string
): string {
  const lines: string[] = [];

  // ── Header ────────────────────────────────────────────────────────────
  lines.push("# Surfaced.ai Content Audit Report");
  lines.push("");
  lines.push(
    `**Date:** ${new Date(report.timestamp).toLocaleString()}  `
  );
  lines.push(
    `**Content Length:** ${report.contentLength.toLocaleString()} characters`
  );
  lines.push("");

  // ── Overall Score ─────────────────────────────────────────────────────
  lines.push(`## Overall Score: ${report.overallScore}/100`);
  lines.push("");

  // ── Pillar Summary Table ──────────────────────────────────────────────
  lines.push("| Pillar | Score | Issues |");
  lines.push("|--------|------:|-------:|");
  for (const pillar of report.pillars) {
    const issueCount = pillar.issues.length;
    const status = issueCount === 0 ? "✅ None" : `${issueCount}`;
    lines.push(
      `| ${pillar.pillar} | ${pillar.score}/100 | ${status} |`
    );
  }
  lines.push("");

  // ── Per-Pillar Details ────────────────────────────────────────────────
  for (const pillar of report.pillars) {
    lines.push(`## ${pillar.pillar} — ${pillar.score}/100`);
    lines.push("");

    if (pillar.issues.length === 0) {
      lines.push("✅ No issues found.");
    } else {
      for (const issue of pillar.issues) {
        const severityLabel = `**[${issue.severity.toUpperCase()}]**`;
        lines.push(`- ${severityLabel} **${issue.title}**`);
        lines.push(`  - ${issue.description}`);
        lines.push(`  - 💡 *${issue.suggestion}*`);
      }
    }

    lines.push("");
  }

  // ── Original Content (optional) ───────────────────────────────────────
  if (originalContent) {
    lines.push("---");
    lines.push("");
    lines.push("## Audited Content");
    lines.push("");
    lines.push("```");
    lines.push(originalContent);
    lines.push("```");
    lines.push("");
  }

  // ── Footer ────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push("");
  lines.push(
    "*Generated by [Surfaced.ai](https://surfaced.ai) — See if your content actually gets found.*"
  );
  lines.push("");

  return lines.join("\n");
}
